#!/bin/sh

REPO_URL=$(ruby ~/repo_url $(pwd))

ansible-playbook --verbose -i playbooks/hosts playbooks/deploy.yml \
  --private-key ~/.ssh/intolerable-awful-river \
  --extra-vars "repo_url=$REPO_URL"
