#!/bin/sh

APP_NAME=$1
REPO_URL=$(./repo_url https://git.exosuit.io/$APP_NAME.git)

ansible-playbook --verbose -i hosts deploy.yml \
  --private-key ~/.ssh/intolerable-awful-river \
  --extra-vars "repo_url=$REPO_URL"
