- hosts: localhost
  gather_facts: false

  tasks:
    - name: Provision instance
      ec2:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        key_name: intolerable-awful-river
        instance_type: t2.micro
        image: ami-05c1fa8df71875112
        wait: yes
        count: 1
        region: us-east-2
        instance_tags:
          Origin: Exosuit
      register: result
    - local_action: copy content={{ result }} dest={{ result_filename }}
