#!/usr/bin/env ruby

require 'netrc'
require 'open3'

netrc_file_path = "#{File.expand_path('~')}/.netrc"
raise 'netrc file missing' unless File.exist?(netrc_file_path)
username, password = Netrc.read(netrc_file_path)['git.exosuit.io']
repo_url = ARGV[0]

puts "https://#{username}:#{password}@" + repo_url.split('https://').last
